# You can create the client id and secret here: https://profile.intra.42.fr/oauth/applications/new
client_id: ""
client_secret: ""
# Defaults to profile if omitted
scopes: [
    "public",
    "projects",
    "profile",
    "elearning",
    "tig",
    "forum",
]
#token_endpoint: #Defaults to "https://api.intra.42.fr/oauth/token"
#api_endpoint: #Defaults to "https://api.intra.42.fr/v2"